### ISSUE TITLE
Build fails on both luarocks and make

### ISSUE THREAD

**Issue by nikneym** [neoxic/lua-mbedtls#2]
Hi, when I try to update the library with luarocks I get this error (output of `sudo luarocks install lua-mbedtls`):
```shell
Installing https://luarocks.org/lua-mbedtls-0.2.0-1.src.rock

lua-mbedtls 0.2.0-1 depends on lua >= 5.1 (5.1-1 provided by VM)
gcc -O2 -fPIC -I/usr/local/include -c src/base64.c -o src/base64.o -I/usr/local/include
gcc -O2 -fPIC -I/usr/local/include -c src/main.c -o src/main.o -I/usr/local/include
gcc -O2 -fPIC -I/usr/local/include -c src/md.c -o src/md.o -I/usr/local/include
gcc -O2 -fPIC -I/usr/local/include -c src/ssl.c -o src/ssl.o -I/usr/local/include
src/ssl.c:31:10: fatal error: mbedtls/certs.h: No such file or directory
   31 | #include <mbedtls/certs.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

Error: Build error: Failed compiling object src/ssl.o
```
I also tried to build it with CMake & make but got similar issues. libmbedtls-dev is installed on my system but `ls /usr/local/include/mbedtls | grep certs` returns nothing.

**Comment by neoxic** [comment]
I assume you are on macOS and have installed mbedtls 3.0 via Homebrew. The problem is that Mbed TLS 3.0 is immature and its API is not backward compatible with 2.x. With time, I'll add support for it

Also, due to this issue - https://github.com/ARMmbed/mbedtls/issues/5184#issuecomment-986429214 - it can't be used with lua-mbedtls as of today.

Your best bet is to downgrade to Mbed TLS 2.x.

**Comment by nikneym** [comment]
I'm actually on Ubuntu 20.04 and installed mbedTLS via building from source. As you've claimed, downgrading mbedTLS to 2.28.0 and rebuilding worked, thanks! Version 3.1.0 seems to have breaking changes for the library.

**Comment by neoxic** [comment]
As a side note, it looks like Ubuntu 20.04 has an official package named `libmbedtls-dev_2.16.4`. You might want to try to install that instead of building from source.

**Comment by neoxic** [comment]
FYI: dd6c2e6a added support for MbedTLS 3.x
