### ISSUE TITLE
I/O blocks indefinitely on `luasocket`

### ISSUE THREAD

**Issue by nikneym** [neoxic/lua-mbedtls#4]
When socket is made non-blocking with setting timeout to zero, it gets blocked indefinitely and won't be able to write to socket. Same is happening with read too. Works fine with blocking sockets or any value but zero, though.

In order to reproduce;
```lua
local socket = require 'socket'
local ssl = require 'mbedtls.ssl'

local function read(h, n)
  return assert(h:receive(n))
end

local function write(h, s)
  return assert(h:send(s))
end

local tcp = assert(socket.connect('google.com', 443))
tcp:settimeout(0)
local cfg = ssl.newconfig('tls-client')
local ctx = ssl.newcontext(cfg, read, write, tcp)

repeat -- never gets out of this loop
  local bytes_written = ctx:write('GET / HTTP/1.1\r\nHost: google.com\r\n\r\n')
until bytes_written
```

**Comment by neoxic** [comment]
You can't simply take a piece of blocking code, turn on non-blocking mode and expect it to just work.

First, you must study how non-blocking sockets work and how they are different from blocking sockets.
Second, you need to come up with a working non-blocking plain text TCP client example, i.e. the one without TLS.
And finally, you will need to modify the working non-blocking code in such a way that I/O operations are wrapped up using lua-mbedtls API.

Closing this as unrelated to lua-mbedtls...
